language: python
python: 
  - "3.6"

addons:
  postgresql: "9.6"
  

env:
  - DJANGO=2.1 DB=postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database testdb;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - coverage run --source='authors' manage.py test
  - coverage report -m

after_success:
  - coveralls
